version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: main
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - jas88
- package-ecosystem: "dotnet-sdk"
  directory: "/"
  schedule:
    interval: weekly
