dist: bionic
os: linux
language: generic

cache:
  directories:
  - $HOME/.nuget

addons:
  postgresql: "10"
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    - sourceline: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'

env:
  global:
  - MSSQL_SA_PASSWORD="YourStrong!Passw0rd"
  - ACCEPT_EULA=Y
  - MSSQL_PID='developer'

services:
  - postgresql
  - mysql

before_install:
- sudo apt-get install -y --no-install-recommends mssql-tools mssql-server dotnet-runtime-2.2 dotnet-sdk-3.1
- sudo /opt/mssql/bin/mssql-conf -n setup accept-eula

script:
 - dotnet restore
 - dotnet build
 - dotnet test
 - dotnet pack NuGet/FAnsi.NuGet.csproj -c Release -p:NuspecFile=NuGet/FAnsi.NuGet.nuspec
 - ls -lh NuGet/*.nupkg
 - if [ -z "$TRAVIS_TAG" ]; then travis_terminate 0; fi
 - dotnet nuget push NuGet/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY || true