dist: bionic
os: linux
language: generic

cache:
  directories:
  - $HOME/.nuget

addons:
  postgresql: "10"
  apt:
    sources:
    - sourceline 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main'
      key_url: 'https://download.mono-project.com/repo/xamarin_ring.gpg'
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    - sourceline: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'

env:
  global:
  - MSSQL_SA_PASSWORD="YourStrong!Passw0rd"
  - ACCEPT_EULA=Y
  - MSSQL_PID='developer'

services:
  - postgresql
  - mysql

before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- sudo apt-get install -y --no-install-recommends mssql-tools mssql-server dotnet-runtime-2.2 dotnet-sdk-3.1 nuget
- sudo /opt/mssql/bin/mssql-conf -n setup accept-eula

script:
 - dotnet restore
 - dotnet build
 - dotnet test
 - cd NuGet
 - nuget pack FAnsi.NuGet.nuspec -Properties Configuration=Release -IncludeReferencedProjects -Symbols -Version $(fgrep Version ../SharedAssemblyInfo.cs|cut -d'"' -f2|head -n1)
 - ls -lh *.nupkg
 - if [ -z "$TRAVIS_TAG" ]; then travis_terminate $TRAVIS_TEST_RESULT; fi
 - dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY || true