//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAnsi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAnsiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAnsiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAnsi.FAnsiStrings", typeof(FAnsiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; appears in bulk insert DataTable but not in destination table &apos;{1}&apos;.
        /// </summary>
        public static string BulkCopy_ColumnNotInDestinationTable {
            get {
                return ResourceManager.GetString("BulkCopy_ColumnNotInDestinationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string keyword &apos;{0}&apos; did not support supplied value.
        /// </summary>
        public static string ConnectionStringKeyword_ValueNotSupported {
            get {
                return ResourceManager.GetString("ConnectionStringKeyword_ValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTable completed but TableCreated property was not correctly set by the implementing Helper API.
        /// </summary>
        public static string DiscoveredDatabase_CreateTableDidNotPopulateTableCreatedProperty {
            get {
                return ResourceManager.GetString("DiscoveredDatabase_CreateTableDidNotPopulateTableCreatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} does not exist so cannot be dropped.
        /// </summary>
        public static string DiscoveredDatabase_DatabaseDoesNotExistSoCannotBeDropped {
            get {
                return ResourceManager.GetString("DiscoveredDatabase_DatabaseDoesNotExistSoCannotBeDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseColumnRequest for column {0} must have either TypeRequested or ExplicitDbType.
        /// </summary>
        public static string DiscoveredDatabaseHelper_CreateTable_DatabaseColumnRequestMustHaveEitherTypeRequestedOrExplicitDbType {
            get {
                return ResourceManager.GetString("DiscoveredDatabaseHelper_CreateTable_DatabaseColumnRequestMustHaveEitherTypeReque" +
                        "stedOrExplicitDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name cannot be null.
        /// </summary>
        public static string DiscoveredDatabaseHelper_GetCreateTableSql_Table_name_cannot_be_null {
            get {
                return ResourceManager.GetString("DiscoveredDatabaseHelper_GetCreateTableSql_Table_name_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resize DataType because it does not have a reference to a Column to which it belongs (possibly you are trying to resize a data type associated with a TableValuedFunction Parameter?).
        /// </summary>
        public static string DiscoveredDataType_AlterTypeTo_Cannot_resize_DataType_because_it_does_not_have_a_reference_to_a_Column_to_which_it_belongs {
            get {
                return ResourceManager.GetString("DiscoveredDataType_AlterTypeTo_Cannot_resize_DataType_because_it_does_not_have_a_" +
                        "reference_to_a_Column_to_which_it_belongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink column, number of digits after the decimal point is currently {0} and you asked to set it to {1} (Current SQLType is {2}).
        /// </summary>
        public static string DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_after_the_decimal_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_after_the_decima" +
                        "l_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink column, number of digits before the decimal point is currently {0} and you asked to set it to {1} (Current SQLType is {2}).
        /// </summary>
        public static string DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_before_the_decimal_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_before_the_decim" +
                        "al_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2_" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal attempt to resize column to a smaller size.  You can only grow columns.  Request was to convert from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string DiscoveredDataType_Resize_CannotResizeSmaller {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_CannotResizeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType cannot be resized to decimal because it is of data type {0}.
        /// </summary>
        public static string DiscoveredDataType_Resize_DataType_cannot_be_resized_to_decimal_because_it_is_of_data_type__0_ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_DataType_cannot_be_resized_to_decimal_because_it_is_of_" +
                        "data_type__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found at least one cycle in relationship dependency.
        /// </summary>
        public static string RelationshipTopologicalSort_FoundCircularDependencies {
            get {
                return ResourceManager.GetString("RelationshipTopologicalSort_FoundCircularDependencies", resourceCulture);
            }
        }
    }
}
