//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAnsi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAnsiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAnsiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAnsi.FAnsiStrings", typeof(FAnsiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateCustomLineCollection is missing some (but not all) Axis components.
        /// </summary>
        public static string AggregateCustomLineCollection_Validate_AggregateCustomLineCollection_is_missing_some__but_not_all__Axis_components {
            get {
                return ResourceManager.GetString("AggregateCustomLineCollection_Validate_AggregateCustomLineCollection_is_missing_s" +
                        "ome__but_not_all__Axis_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; appears in bulk insert DataTable but not in destination table &apos;{1}&apos;.
        /// </summary>
        public static string BulkCopy_ColumnNotInDestinationTable {
            get {
                return ResourceManager.GetString("BulkCopy_ColumnNotInDestinationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string keyword &apos;{0}&apos; did not support supplied value.
        /// </summary>
        public static string ConnectionStringKeyword_ValueNotSupported {
            get {
                return ResourceManager.GetString("ConnectionStringKeyword_ValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not combine Types &apos;{0}&apos; and &apos;{1}&apos; because they were of differing Types and neither Type appeared in the PreferenceOrder.
        /// </summary>
        public static string DatabaseTypeRequest_Max_Could_not_combine_Types___0___and___1___because_they_were_of_differing_Types_and_neither_Type_appeared_in_the_PreferenceOrder {
            get {
                return ResourceManager.GetString("DatabaseTypeRequest_Max_Could_not_combine_Types___0___and___1___because_they_were" +
                        "_of_differing_Types_and_neither_Type_appeared_in_the_PreferenceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable column {0} was of DataType {1}, this is not allowed.  Use String for untyped data.
        /// </summary>
        public static string DataTable_Column__0__was_of_DataType__1___this_is_not_allowed___Use_String_for_untyped_data {
            get {
                return ResourceManager.GetString("DataTable_Column__0__was_of_DataType__1___this_is_not_allowed___Use_String_for_un" +
                        "typed_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse &apos;{0}&apos; to a valid DateTime.
        /// </summary>
        public static string DateTimeTypeDecider_ParseImpl_Could_not_parse___0___to_a_valid_DateTime {
            get {
                return ResourceManager.GetString("DateTimeTypeDecider_ParseImpl_Could_not_parse___0___to_a_valid_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecideTypesForStrings abstract base was not passed any typesSupported by implementing derived class.
        /// </summary>
        public static string DecideTypesForStrings_DecideTypesForStrings_DecideTypesForStrings_abstract_base_was_not_passed_any_typesSupported_by_implementing_derived_class {
            get {
                return ResourceManager.GetString("DecideTypesForStrings_DecideTypesForStrings_DecideTypesForStrings_abstract_base_w" +
                        "as_not_passed_any_typesSupported_by_implementing_derived_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse string value &apos;{0}&apos; with Decider Type:{1}.
        /// </summary>
        public static string DecideTypesForStrings_Parse_Could_not_parse_string_value___0___with_Decider_Type__1_ {
            get {
                return ResourceManager.GetString("DecideTypesForStrings_Parse_Could_not_parse_string_value___0___with_Decider_Type_" +
                        "_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTable completed but TableCreated property was not correctly set by the implementing Helper API.
        /// </summary>
        public static string DiscoveredDatabase_CreateTableDidNotPopulateTableCreatedProperty {
            get {
                return ResourceManager.GetString("DiscoveredDatabase_CreateTableDidNotPopulateTableCreatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} does not exist so cannot be dropped.
        /// </summary>
        public static string DiscoveredDatabase_DatabaseDoesNotExistSoCannotBeDropped {
            get {
                return ResourceManager.GetString("DiscoveredDatabase_DatabaseDoesNotExistSoCannotBeDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseColumnRequest for column {0} must have either TypeRequested or ExplicitDbType.
        /// </summary>
        public static string DiscoveredDatabaseHelper_CreateTable_DatabaseColumnRequestMustHaveEitherTypeRequestedOrExplicitDbType {
            get {
                return ResourceManager.GetString("DiscoveredDatabaseHelper_CreateTable_DatabaseColumnRequestMustHaveEitherTypeReque" +
                        "stedOrExplicitDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name cannot be null.
        /// </summary>
        public static string DiscoveredDatabaseHelper_GetCreateTableSql_Table_name_cannot_be_null {
            get {
                return ResourceManager.GetString("DiscoveredDatabaseHelper_GetCreateTableSql_Table_name_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resize DataType because it does not have a reference to a Column to which it belongs (possibly you are trying to resize a data type associated with a TableValuedFunction Parameter?).
        /// </summary>
        public static string DiscoveredDataType_AlterTypeTo_Cannot_resize_DataType_because_it_does_not_have_a_reference_to_a_Column_to_which_it_belongs {
            get {
                return ResourceManager.GetString("DiscoveredDataType_AlterTypeTo_Cannot_resize_DataType_because_it_does_not_have_a_" +
                        "reference_to_a_Column_to_which_it_belongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send resize SQL:{0}.
        /// </summary>
        public static string DiscoveredDataType_AlterTypeTo_Failed_to_send_resize_SQL__0_ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_AlterTypeTo_Failed_to_send_resize_SQL__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink column, number of digits after the decimal point is currently {0} and you asked to set it to {1} (Current SQLType is {2}).
        /// </summary>
        public static string DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_after_the_decimal_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_after_the_decima" +
                        "l_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot shrink column, number of digits before the decimal point is currently {0} and you asked to set it to {1} (Current SQLType is {2}).
        /// </summary>
        public static string DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_before_the_decimal_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2__ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_Cannot_shrink_column__number_of_digits_before_the_decim" +
                        "al_point_is_currently__0__and_you_asked_to_set_it_to__1___Current_SQLType_is__2_" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal attempt to resize column to a smaller size.  You can only grow columns.  Request was to convert from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string DiscoveredDataType_Resize_CannotResizeSmaller {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_CannotResizeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType cannot be resized to decimal because it is of data type {0}.
        /// </summary>
        public static string DiscoveredDataType_Resize_DataType_cannot_be_resized_to_decimal_because_it_is_of_data_type__0_ {
            get {
                return ResourceManager.GetString("DiscoveredDataType_Resize_DataType_cannot_be_resized_to_decimal_because_it_is_of_" +
                        "data_type__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper &apos;{0}&apos; tried to create database &apos;{1}&apos; but the database didn&apos;t exist after the creation attempt.
        /// </summary>
        public static string DiscoveredServer_CreateDatabase_Helper___0___tried_to_create_database___1___but_the_database_didn_t_exist_after_the_creation_attempt {
            get {
                return ResourceManager.GetString("DiscoveredServer_CreateDatabase_Helper___0___tried_to_create_database___1___but_t" +
                        "he_database_didn_t_exist_after_the_creation_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server &apos;{0}&apos; after timeout of {1} milliseconds).
        /// </summary>
        public static string DiscoveredServer_TestConnection_Could_not_connect_to_server___0___after_timeout_of__1__milliseconds_ {
            get {
                return ResourceManager.GetString("DiscoveredServer_TestConnection_Could_not_connect_to_server___0___after_timeout_o" +
                        "f__1__milliseconds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscoverColumn failed, could not find column called &apos;{0}&apos; in table &apos;{1}&apos;.
        /// </summary>
        public static string DiscoveredTable_DiscoverColumn_DiscoverColumn_failed__could_not_find_column_called___0___in_table___1__ {
            get {
                return ResourceManager.GetString("DiscoveredTable_DiscoverColumn_DiscoverColumn_failed__could_not_find_column_calle" +
                        "d___0___in_table___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert failed, could not find column called &apos;{0}&apos; in table &apos;{1}&apos;.
        /// </summary>
        public static string DiscoveredTable_Insert_Insert_failed__could_not_find_column_called___0___in_table___1__ {
            get {
                return ResourceManager.GetString("DiscoveredTable_Insert_Insert_failed__could_not_find_column_called___0___in_table" +
                        "___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create primary key on table {0} using columns ({1}).
        /// </summary>
        public static string DiscoveredTableHelper_CreatePrimaryKey_Failed_to_create_primary_key_on_table__0__using_columns___1__ {
            get {
                return ResourceManager.GetString("DiscoveredTableHelper_CreatePrimaryKey_Failed_to_create_primary_key_on_table__0__" +
                        "using_columns___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename is not supported for TableType {0}.
        /// </summary>
        public static string DiscoveredTableHelper_RenameTable_Rename_is_not_supported_for_TableType__0_ {
            get {
                return ResourceManager.GetString("DiscoveredTableHelper_RenameTable_Rename_is_not_supported_for_TableType__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesser does not support being passed hard typed objects (e.g. int) mixed with untyped objects (e.g. string).  We were adjusting to compensate for object &apos;{0}&apos; which is of Type &apos;{1}&apos;, we were previously passed a &apos;{2}&apos; type.
        /// </summary>
        public static string Guesser_AdjustToCompensateForValue_GuesserPassedMixedTypeValues {
            get {
                return ResourceManager.GetString("Guesser_AdjustToCompensateForValue_GuesserPassedMixedTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Type Decider exists for Type:{0}.
        /// </summary>
        public static string Guesser_ThrowIfNotSupported_No_Type_Decider_exists_for_Type__0_ {
            get {
                return ResourceManager.GetString("Guesser_ThrowIfNotSupported_No_Type_Decider_exists_for_Type__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation found for ADO.Net object of Type {0}.
        /// </summary>
        public static string ImplementationManager_GetImplementation_No_implementation_found_for_ADO_Net_object_of_Type__0_ {
            get {
                return ResourceManager.GetString("ImplementationManager_GetImplementation_No_implementation_found_for_ADO_Net_objec" +
                        "t_of_Type__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No implementation found for DatabaseType {0}.
        /// </summary>
        public static string ImplementationManager_GetImplementation_No_implementation_found_for_DatabaseType__0_ {
            get {
                return ResourceManager.GetString("ImplementationManager_GetImplementation_No_implementation_found_for_DatabaseType_" +
                        "_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos;did not exist.
        /// </summary>
        public static string ImplementationManager_Load_Directory___0__did_not_exist {
            get {
                return ResourceManager.GetString("ImplementationManager_Load_Directory___0__did_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String passed to EnsureWrapped &apos;{0}&apos; contained separators (not allowed).  Prohibited Separator is &apos;{1}&apos;.
        /// </summary>
        public static string QuerySyntaxHelper_EnsureWrapped_String_passed_to_EnsureWrapped___0___contained_separators__not_allowed____Prohibited_Separator_is___1__ {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_EnsureWrapped_String_passed_to_EnsureWrapped___0___contained_se" +
                        "parators__not_allowed____Prohibited_Separator_is___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not GetParameter for column &apos;{0}&apos;.  See InnerException for details.
        /// </summary>
        public static string QuerySyntaxHelper_GetParameter_Could_not_GetParameter_for_column___0__ {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_GetParameter_Could_not_GetParameter_for_column___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line must contain at least one pair of parentheses.
        /// </summary>
        public static string QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_Line_must_contain_at_least_one_pair_of_parentheses {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_Line_must_contain_at_le" +
                        "ast_one_pair_of_parentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line must not be blank.
        /// </summary>
        public static string QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_Line_must_not_be_blank {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_Line_must_not_be_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of opening and closing parentheses must match.
        /// </summary>
        public static string QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_The_number_of_opening_and_closing_parentheses_must_match {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_SplitLineIntoOuterMostMethodAndContents_The_number_of_opening_a" +
                        "nd_closing_parentheses_must_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not split SQL line because there were {0} instances of the alias regex.  Sql line was: 
        ///{1}.
        /// </summary>
        public static string QuerySyntaxHelper_SplitLineIntoSelectSQLAndAlias_ {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_SplitLineIntoSelectSQLAndAlias_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name &apos;{1}&apos; contained unsupported (by FAnsi) characters.  Unsupported characters are:{2}.
        /// </summary>
        public static string QuerySyntaxHelper_ValidateName__0__name___1___contained_unsupported__by_FAnsi__characters___Unsupported_characters_are__2_ {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_ValidateName__0__name___1___contained_unsupported__by_FAnsi__ch" +
                        "aracters___Unsupported_characters_are__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name &apos;{1}&apos; is too long for the DBMS ({2} supports maximum length of {3}).
        /// </summary>
        public static string QuerySyntaxHelper_ValidateName__0__name___1___is_too_long_for_the_DBMS___2__supports_maximum_length_of__3__ {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_ValidateName__0__name___1___is_too_long_for_the_DBMS___2__suppo" +
                        "rts_maximum_length_of__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name cannot be blank.
        /// </summary>
        public static string QuerySyntaxHelper_ValidateName__0__name_cannot_be_blank {
            get {
                return ResourceManager.GetString("QuerySyntaxHelper_ValidateName__0__name_cannot_be_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found at least one cycle in relationship dependency.
        /// </summary>
        public static string RelationshipTopologicalSort_FoundCircularDependencies {
            get {
                return ResourceManager.GetString("RelationshipTopologicalSort_FoundCircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType {0} does not have an associated IDecideTypesForStrings.
        /// </summary>
        public static string TypeDeciderFactory_Create_DataType__0__does_not_have_an_associated_IDecideTypesForStrings {
            get {
                return ResourceManager.GetString("TypeDeciderFactory_Create_DataType__0__does_not_have_an_associated_IDecideTypesFo" +
                        "rStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CSharp type mapping exists for SQL type &apos;{0}&apos;. TypeTranslater was &apos;{1}&apos;).
        /// </summary>
        public static string TypeTranslater_GetCSharpTypeForSQLDBType_No_CSharp_type_mapping_exists_for_SQL_type___0____TypeTranslater_was___1___ {
            get {
                return ResourceManager.GetString("TypeTranslater_GetCSharpTypeForSQLDBType_No_CSharp_type_mapping_exists_for_SQL_ty" +
                        "pe___0____TypeTranslater_was___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsure what SQL type to use for CSharp Type &apos;{0}&apos;.  TypeTranslater was &apos;{1}&apos;.
        /// </summary>
        public static string TypeTranslater_GetSQLDBTypeForCSharpType_Unsure_what_SQL_type_to_use_for_CSharp_Type___0_____TypeTranslater_was___1__ {
            get {
                return ResourceManager.GetString("TypeTranslater_GetSQLDBTypeForCSharpType_Unsure_what_SQL_type_to_use_for_CSharp_T" +
                        "ype___0_____TypeTranslater_was___1__", resourceCulture);
            }
        }
    }
}
