//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAnsi.Implementations.MicrosoftSQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAnsi.Implementations.MicrosoftSQL.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkInsert failed on data row {0}:{1}.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_AttemptLineByLineInsert_BulkInsert_failed_on_data_row__0___1_ {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_AttemptLineByLineInsert_BulkInsert_failed_on_data_row__0___1" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkInsert failed on data row {0} the complaint was about source column &lt;&lt;{1}&gt;&gt; which had value &lt;&lt;{2}&gt;&gt; destination data type was &lt;&lt;{3}&gt;&gt;{4}{5}.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_AttemptLineByLineInsert_BulkInsert_failed_on_data_row__0__the_complaint_was_about_source_column____1____which_had_value____2____destination_data_type_was____3____4__5_ {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_AttemptLineByLineInsert_BulkInsert_failed_on_data_row__0__th" +
                        "e_complaint_was_about_source_column____1____which_had_value____2____destination_" +
                        "data_type_was____3____4__5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Pass Exception:.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_AttemptLineByLineInsert_First_Pass_Exception_ {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_AttemptLineByLineInsert_First_Pass_Exception_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Pass Exception: Bulk insert failed but when we tried to repeat it a line at a time it worked.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_AttemptLineByLineInsert_Second_Pass_Exception__Bulk_insert_failed_but_when_we_tried_to_repeat_it_a_line_at_a_time_it_worked {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_AttemptLineByLineInsert_Second_Pass_Exception__Bulk_insert_f" +
                        "ailed_but_when_we_tried_to_repeat_it_a_line_at_a_time_it_worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Pass Exception: Failed to load data row {0} the following values were rejected by the database: {1}{2}{3}.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_AttemptLineByLineInsert_Second_Pass_Exception__Failed_to_load_data_row__0__the_following_values_were_rejected_by_the_database___1__2__3_ {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_AttemptLineByLineInsert_Second_Pass_Exception__Failed_to_loa" +
                        "d_data_row__0__the_following_values_were_rejected_by_the_database___1__2__3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bulk insert:{0}.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_BulkInsertWithBetterErrorMessages_Failed_to_bulk_insert__0_ {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_BulkInsertWithBetterErrorMessages_Failed_to_bulk_insert__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bulk insert batch, line by line investigation also failed.  InnerException[0] is the original Exception, InnerException[1] is the line by line failure.
        /// </summary>
        internal static string MicrosoftSQLBulkCopy_BulkInsertWithBetterErrorMessages_Failed_to_bulk_insert_batch__line_by_line_investigation_also_failed___InnerException_0__is_the_original_Exception__InnerException_1__is_the_line_by_line_failure {
            get {
                return ResourceManager.GetString("MicrosoftSQLBulkCopy_BulkInsertWithBetterErrorMessages_Failed_to_bulk_insert_batc" +
                        "h__line_by_line_investigation_also_failed___InnerException_0__is_the_original_Ex" +
                        "ception__InnerException_1__is_the_line_by_line_failure", resourceCulture);
            }
        }
    }
}
