name: .NET Core

on:
  push

env:
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "developer"

          
jobs:  
  build:

    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: pgpass4291
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      oracle:
        image: gvenzl/oracle-xe:latest
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: ora
          APP_USER_PASSWORD: zombie
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Disable write flush for CI runs
      run: sudo apt-get install -y libeatmydata1 apt-transport-https curl
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Sql Server
      run: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"
        sudo apt-get install -y --no-install-recommends postgresql mssql-tools mssql-server
        sudo -E /opt/mssql/bin/mssql-conf -n setup accept-eula
    - name: MySQL
      run: |
        sed -i'' -e 's/Pwd=;SslMode=None/Pwd=root;AllowPublicKeyRetrieval=true/' Tests/FAnsiTests/TestDatabases.xml
        sudo systemctl start mysql.service
    - name: Test
      run: dotnet test --logger "console;verbosity=minimal" --nologo
    - name: Pack
      run: |
        mkdir -p NuGet/bin
        ln -sf Release/netstandard2.1 NuGet/bin/
        dotnet pack NuGet/FAnsi.NuGet.csproj -c Release --include-source --include-symbols --nologo -p:NuspecFile=`pwd`/NuGet/FAnsi.NuGet.nuspec -p:NuspecProperties=Version=$(fgrep AssemblyInformationalVersion SharedAssemblyInfo.cs|cut -d'"' -f2) -p:SymbolPackageFormat=snupkg
    - name: Nuget push
      if: contains(github.ref,'refs/tags/')
      run: dotnet nuget push NuGet/bin/Release/HIC.FAnsiSql.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }} --skip-duplicate
    - name: Store created nupkg files
      uses: actions/upload-artifact@v3
      with:
        path: NuGet/bin/Release/*.nupkg
        retention-days: 1
    - name: Upload release binaries
      if: contains(github.ref,'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: NuGet/bin/Release/*.nupkg
        file_glob: true
        overwrite: true
